db.cerpen.insertOne({
  _id: ObjectId(),
  judul: "Manajemen Basis Data",
  penulis: "Dita Yustianisa",
  penerbit: "Informatika Majene",
  tahun_terbit: 2025,
  kategori: "Teknik Informatika",
  isbn: "978-623-1234-567-8",
  stok: 10,
  lokasi: "Rak A3",
});

// menambahkan banyak dokumen sekaligus
db.cerpen.insertMany([
  {
    _id: ObjectId(),
    judul: "Natural Language Processing",
    penulis: "Dita Yustianisa",
    penerbit: "Informatika Majene",
    tahun_terbit: 2021,
    kategori: "Informatika",
    isbn: "978-623-1234-467-8",
    stok: 12,
    lokasi: "Rak A3",
  },
  {
    _id: ObjectId(),
    judul: "Algoritma dan Pemrograman",
    penulis: "Dian Purnama",
    penerbit: "Informatika Bandung",
    tahun_terbit: 2021,
    kategori: "Teknik Informatika",
    isbn: "978-623-1234-567-8",
    stok: 10,
    lokasi: "Rak A3",
  },
  {
    _id: ObjectId(),
    judul: "Basis Data Lanjut",
    penulis: "Andi Setiawan",
    penerbit: "Graha Ilmu",
    tahun_terbit: 2020,
    kategori: "Sistem Informasi",
    isbn: "978-623-8765-432-1",
    stok: 7,
    lokasi: "Rak B1",
  },
  {
    _id: ObjectId(),
    judul: "Struktur Data",
    penulis: "Sri Wahyuni",
    penerbit: "Andi Publisher",
    tahun_terbit: 2019,
    kategori: "Ilmu Komputer",
    isbn: "978-602-1234-987-6",
    stok: 5,
    lokasi: "Rak C2",
  },
]);
